#!/bin/bash
#download tomcat from china

Version=$(curl -Lks https://mirrors.shu.edu.cn/apache/tomcat/tomcat-8/ | grep  "<a href=" | awk -F'["/]?' '/v[0-9]/{print $11}')
Workdir="/usr/local/src"
TOMCAT_USER=tomcat
if ! id $TOMCAT_USER >/dev/null 2>&1;then
    useradd -s /bin/bash $TOMCAT_USER
fi
#if you wish to change the installation directory, just replcae Workdir with the doc which one you wish
if [ ! -f apache-tomcat-`echo ${Version} | tr -d "v"`.tar.gz ];then
    wget https://mirrors.shu.edu.cn/apache/tomcat/tomcat-8/$Version/bin/apache-tomcat-`echo ${Version} | tr -d "v"`.tar.gz
    if [ "$PWD" = "$Workdir" ];then
	tar -zxvf apache-tomcat-`echo ${Version} | tr -d "v"`.tar.gz
    else
	tar -zxvf apache-tomcat-`echo ${Version} | tr -d "v"`.tar.gz -C $Workdir
    fi
else
        tar -zxvf apache-tomcat-`echo ${Version} | tr -d "v"`.tar.gz -C $Workdir
fi

#set enviromental variables with jdk for tomcat
sed -ir "110 a"JAVA_HOME=$Workdir/jdk1.8.0_201"" $Workdir/apache-tomcat-`echo ${Version} | tr -d "v"`/bin/catalina.sh
sed -ir "110 a"CATALINA_HOME=$Workdir/apache-tomcat-`echo ${Version} | tr -d "v"`"" $Workdir/apache-tomcat-`echo ${Version} | tr -d "v"`/bin/catalina.sh
#set enviromental variables for jdk
if ! egrep JAVA_HOME /etc/profile >/dev/null 2>&1;then
    echo -e "JAVA_HOME=/usr/local/src/jdk1.8.0_201\nJRE_HOME=/usr/local/src/jdk1.8.0_201/jre\nexport PATH=$PATH:$JAVA_HOME/bin:$JRE_HOME/bin" >>/etc/profile
fi
JAVA_HOME=$Workdir/jdk1.8.0_201
JRE_HOME=$Workdir/jdk1.8.0_201/jre
export PATH=$PATH:$JAVA_HOME/bin:$JRE_HOME/bin
cat >/etc/init.d/tomcat <<EOF
#!/bin/bash
#for start|stop|restart tomcat with user tomcat
#chkconfig:2345 10 90
#description:myservice
if [ -f /etc/init.d/functions ];then
	. /etc/init.d/functions
elif [ -f /etc/rc.d/init.d/functions ];then
        . /etc/rc.d/init.d/functions
else
	echo -e "\atomcat: unable to locate functions lib.Connot continue."
	exit -1
fi

prog=tomcat
TOMCAT_USER=tomcat
CATALANA_HOME=$Workdir/apache-tomcat-`echo ${Version} | tr -d "v"`
case "\$1" in
start)
    echo "starting Tomcat..."
    su \$TOMCAT_USER -c \$CATALANA_HOME/bin/startup.sh
    ;;
stop)
    echo "stopping tomcat..."
    \$CATALANA_HOME/bin/shutdown.sh
    ;;
restart)
    echo "stopping tomcat..."
    \$CATALANA_HOME/bin/shutdown.sh
    sleep 2
    echo "starting tomcat..."
    su \$TOMCAT_USER -c \$CATALANA_HOME/bin/startup.sh
    ;;
status)
    if [ -f $LOCKFILE ];then
    	echo $0 started.
    else
    	echo $0 stopped.
    fi
    ;;
*)
    echo "Usage:\$prog{start|stop|restart}"
    ;;
esac
exit 0
EOF
chown -R $TOMCAT_USER:$TOMCAT_USER $Workdir/apache-tomcat-`echo ${Version} | tr -d "v"`
chmod +x /etc/init.d/tomcat
chkconfig --add tomcat
service tomcat restart
